# 입양 간 동물 중 가장 오래 보호소에 있었던 동물 3마리 > 이름, 보호 시작일
# 보호 시작일 순
SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_INS I RIGHT OUTER JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
ORDER BY DATEDIFF(O.DATETIME, I.DATETIME) DESC
LIMIT 2;