# 중고 거래 게시물 3건 이상 등록한 사용자 > 사용자 ID, 닉네임, 전체주소, 전화번호
SELECT U.USER_ID, U.NICKNAME, CONCAT(U.CITY,' ',U.STREET_ADDRESS1,' ', U.STREET_ADDRESS2) AS 전체주소, CONCAT(SUBSTRING(U.TLNO, 1, 3),'-',SUBSTRING(U.TLNO, 4, 4), '-', SUBSTRING(U.TLNO, 8, 4)) AS 전화번호
FROM USED_GOODS_BOARD G JOIN USED_GOODS_USER U ON G.WRITER_ID = U.USER_ID
GROUP BY G.WRITER_ID
HAVING COUNT(*) >= 3
ORDER BY U.USER_ID DESC
