# 보호소 들어올 땐 중성화X, 보호소 나갈 땐 중성화O > ID, 종, 이름
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.SEX_UPON_INTAKE LIKE 'Intact%' AND (O.SEX_UPON_OUTCOME = 'Spayed Female' OR O.SEX_UPON_OUTCOME = 'Neutered Male')
ORDER BY I.ANIMAL_ID ASC