# 년, 월, 성별 별로 상품을 구매한 회원수
# 성별 정보가 없는 경우 결과에서 제외
# 년, 월, 성별을 기준으로 오름차순
SELECT YEAR(O.SALES_DATE), MONTH(O.SALES_DATE), U.GENDER, COUNT(DISTINCT O.USER_ID) AS USERS
FROM USER_INFO U JOIN ONLINE_SALE O ON U.USER_ID = O.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE), U.GENDER
ORDER BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE), U.GENDER