-- 생일이 3월인 여성 ID, 이름, 성별, 생년월일
SELECT M.MEMBER_ID, M.MEMBER_NAME, M.GENDER,
    DATE_FORMAT(M.DATE_OF_BIRTH, '%Y-%m-%d')
FROM MEMBER_PROFILE M
WHERE M.TLNO IS NOT NULL AND
    MONTH(DATE_OF_BIRTH) = 3 AND
    M.GENDER = 'W'
ORDER BY M.MEMBER_ID ASC;